### ISSUE TITLE
Please add some installation instructions

### ISSUE THREAD

**Issue by ottok** [szepeviktor/tiny-cache#2]
Hello!

Please add some installation instructions.

If I just copy everything in this repo to mu-plugins it yields:
> [24-Aug-2017 19:52:32 UTC] PHP Parse error:  syntax error, unexpected '$found' (T_VARIABLE) in /data/wordpress/htdocs/wp-content/mu-plugins/using-transients/tiny-cache_transient.php on line 29

Also the installation instructions could include some tips on how to verify if the caches are active, e.g. what key names to search from the cache or something. I now removed this subdirectory, but I don't know if the rest of the files continue to work as expected or not.

**Comment by szepeviktor** [comment]
I am sorry. The `/using-transients` directory contains clone/s of the plugins.
The difference is direct WP cache access vs. transient usage.

And there **was** a big syntax error: https://github.com/szepeviktor/tiny-cache/commit/3af6596c38dd25f4162488406a7d839cb0bdf155

**Comment by szepeviktor** [comment]
`/using-transients` is moved to another repo.

Thank you!
