### ISSUE TITLE
Changing cache key - nav menu args

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/tiny-cache#5]
From #4
Could you explain your change?
https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/class-wp-nav-menu-args.php
What property changes when?

**Comment by colinleroy** [comment]
Hi :)

when the `pre_wp_nav_menu` filter calls `get_nav_menu()`, we look for a cache key encoding `$args` to json. the json looks like:
```json
{"menu":"","container":"div","container_class":"","container_id":"","container_aria_label":"","menu_class":"menu","menu_id":"nav-header","echo":true,"fallback_cb":false,"before":"","after":"","link_before":"","link_after":"","items_wrap":"<ul id=\"%1$s\" class=\"%2$s\">%3$s<\/ul>","item_spacing":"preserve","depth":0,"walker":"","theme_location":"header"}
```
Then, if we don't find that key in cache, the WordPress `wp_nav_menu()` gets called, does its job, and at line 146, does:
```php
        if ( empty( $args->menu ) ) {
                $args->menu = $menu;
        }
```
Then we arrive into `save_nav_menu()`, and store the generated menu using `json_encoding` of `$args` too. But now, `$args` look like:
```json
{"menu":{"term_id":54,"name":"Header fr","slug":"header-fr","term_group":0,"term_taxonomy_id":54,"taxonomy":"nav_menu","description":"","parent":0,"count":14,"filter":"raw"},"container":"div","container_class":"","container_id":"","container_aria_label":"","menu_class":"menu","menu_id":"nav-header","echo":true,"fallback_cb":false,"before":"","after":"","link_before":"","link_after":"","items_wrap":"<ul id=\"%1$s\" class=\"%2$s\">%3$s<\/ul>","item_spacing":"preserve","depth":0,"walker":"","theme_location":"header"}
```
So the cache never saves the menu with the same key as it's looking for it, rendering the cache useless.
This is why this change uses `"nav_menu-$menu_id"` as key.

**Comment by szepeviktor** [comment]
Thank you for your explanation.
You seem to be right ...and the only user of this class :)
